### ISSUE TITLE
Clean site

### ISSUE THREAD

**Issue by LeonardBesseau** [gen-classroom/projet-besseau_cerottini_maziero_ogi#32]
Need to add the command clean

`statique clean`

The command should delete the build folder

optimiste: 30 min
pessimiste: 2h
attendu: 1h

**Comment by LeonardBesseau** [comment]
@MazieroMarco failed to see test was incorrect. I propose to remove him from project leader as a punition

**Comment by MazieroMarco** [comment]
> 
> 
> @MazieroMarco failed to see the test was incorrect. I propose to remove him from project leader as a punition

As chief commander, I strongly disagree with your opinion. The test was indeed successful and a just though you could not do better, so I merged your humble pull request.

Yours faithfully, 

Marco Maziero
